### ISSUE TITLE
Add an enabled option

### ISSUE THREAD

**Issue by junichi11** [commonquail/netbeans-eof-line-feed#3]
This is a feature request.

Could you add an enabled/disabled option?

Currently, If we want to disable this plugin's feature, we have to deactivate the plugin (or uninstall). It means that we have to restart the IDE.

Thanks.

**Comment by commonquail** [comment]
That's a good point.

I don't know of a way to deactivate a plugin without restarting but even if that's possible it requires going through the somewhat unwieldy plugin menu--much less ergonomic than, say, a menu entry.

How frequently do you need this? What kind of files are compromised by the linefeed? How do you see yourself using this?

I have given much thought to toggling. The most naive solution -- enable/disable -- ought to be a small implementation effort (allowing for persistent storage, which may or may not be nice to have), but is simplistic and introduces an unnecessary manual task. At the other extreme is the ability to customize line endings per file type, allowing any combination of `<no eol>`, `CR`, and `LF` and some sensible defaults (see also #2), but that goes pretty squarely against the working philosophy of, "if you need something other than `LF` you probably have a corner case I am not interested in solving personally". Somewhere between those is the ability to disable the behaviour per file type.

I have not solved this problem because I have not yet needed the problem solved and don't know what the simplest, most ergonomic solution is. Not because I have not acknowledged the problem.

**Comment by junichi11** [comment]
> How frequently do you need this? What kind of files are compromised by the linefeed? How do you see yourself using this?

I need it when I just want to change to an empty file (i.e. I want to remove whole text completely). 
I' m going to add an option for this plugin later. Probably, add just an "enabled" checkbox. If you prefer it, I can send a Pull Request.

Regarding #2 : 
IMHO, perhaps, it would be resolved if a line ending for an existing file is added. (I can be wrong.)

Thanks!

**Comment by commonquail** [comment]
#2 is just another side of the same coin ("`LF` is wrong for case X"). I certainly don't want any _magic_ determining whether to do something and what -- I want everything to be explicit.

How frequently do you clear out, and leave empty, files? Vim also makes it difficult to remove the final linefeed from an "empty" file, and this sounds a bit more like a job for `truncate --size=0 FILE` or `printf '' > FILE`.

If you make a change you are more than welcome to send a PR. Although I reserve the right to reject it I will consider the change in earnest.

Note that I think the test fails to compile for reasons I have not cared sufficiently to address. I also keep meaning to move this to Maven...

**Comment by junichi11** [comment]
I just have such case sometimes. My request is not creating an empty file but adding the option ;) So if you don't want to add it, you can close this issue. If you will implement it, I don't do anything :) 

Thanks.

**Comment by junichi11** [comment]
I'll create a new plugin from scratch by myself. Thanks!
